version: '3'

services:
  redis:
    image: "redis:alpine"
    container_name: local_docker_redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:$PWD/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes

  db:
    image: mysql:8.0.17
    container_name: local-docker-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: rootPw1234
      MYSQL_USER: localTestUser
      MYSQL_PASSWORD: localTestPw1234
      MYSQL_DATABASE: local_docker_db
      TZ: Asia/Seoul
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redis-data:
  mysql_data:

