server:
  port: 8080

spring:
  application:
    name: ${springboot.app.name:japExample}

  datasource:
    url: ${db.url:jdbc:mysql://localhost:3306/local_docker_db?serverTimezone=Asia/Seoul}
    username: ${db.username:localTestUser}
    password: ${db.password:localTestPw1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    sql-script-encoding: UTF-8

  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 200
        max-wait: 20ms
        min-idle: 10
        time-between-eviction-runs: 100ms
    timeout: 100ms

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  file:
    path: ./logs
  level:
    # JPA SQL 쿼리문 로그 확인
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: TRACE
    # JPA SQL 쿼리 bind 값 로그 확인
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE